name: Atualizar EPG Diariamente

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar os arquivos EPG atualizados
      run: |
        # Fonte 1: epgshare01
        curl -L "https://epgshare01.online/epgshare01/epg_ripper_BR1.xml.gz" -o epg1.xml
        
        # Fonte 2: epg.pw (ou outra de sua preferência)
        curl -L "https://epg.pw/xmltv/epg_BR.xml" -o epg2.xml

    - name: Commit e Push das alterações
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add epg1.xml epg2.xml
        git diff-index --quiet HEAD || git commit -m "Atualização automática das fontes de EPG"
        git push
