name: Atualizar EPG Diariamente

on:
  schedule:
    # Roda todos os dias às 06:00 UTC (03:00 no horário de Brasília)
    - cron: '0 6 * * *'
  workflow_dispatch: # Permite forçar a atualização manualmente

# CORREÇÃO DO AVISO: Força as ações a rodarem no Node.js 24 moderno
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Baixar o arquivo EPG atualizado
      run: |
        curl -L "https://epgshare01.online/epgshare01/epg_ripper_BR1.xml" -o epg.xml

    - name: Commit e Push das alterações
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add epg.xml
        git diff-index --quiet HEAD || git commit -m "Atualização automática da EPG"
        git push
